apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
    # volumeSize: 80
    # ssh:
    #   allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: m5.xlarge
  #   desiredCapacity: 2
  #   volumeSize: 100
  #   ssh:
  #     publicKeyPath: ~/.ssh/ec2_id_rsa.pub